### ISSUE TITLE
Hotstar download not working

### ISSUE THREAD

**Issue by priyanshudiwan14** [biezom/hotstarsportslivestreamer#44]

**Comment by priyanshudiwan14** [comment]
paste the link:http://www.hotstar.com/tv/sarabhai-vs-sarabhai-take-2/523/monisha-ki-mannat/1000175396
Available streams:   234p 360p 404p 720p 900p 1080p
write quality (example write 720p):1080p
play or download? (write p or d):d
Starting livestreamer...

The system cannot find the path specified.
Done.
Press any key to continue . . .

**Comment by priyanshudiwan14** [comment]
Please help@biezom

**Comment by shortthirdman** [comment]
I am also facing the same problem @priyanshudiwan14 @biezom . Please help. It occurs only when downloading video from Hotstar

**Comment by 0880** [comment]
Hotstar videos can be downloaded with YOUTUBE-DL.

https://github.com/rg3/youtube-dl
https://youtube-dl.org/downloads/latest/youtube-dl.exe
```
youtube-dl -F "http://www.hotstar.com/tv/sarabhai-vs-sarabhai-take-2/523/monisha-ki-mannat/1000175396"
[HotStar] 1000175396: Downloading JSON metadata
[HotStar] 1000175396: Downloading JIO JSON metadata
[HotStar] 1000175396: Downloading m3u8 information
[info] Available formats for 1000175396:
format code  extension  resolution note
hls-64       mp4        250x140      64k , avc1.66.30, mp4a.40.2
hls-121      mp4        320x180     121k , avc1.66.30, mp4a.40.2
hls-241      mp4        320x180     241k , avc1.66.30, mp4a.40.2
hls-461      mp4        416x234     461k , avc1.66.30, mp4a.40.2
hls-861      mp4        640x360     861k , avc1.66.30, mp4a.40.2
hls-1360     mp4        720x404    1360k , avc1.66.30, mp4a.40.2
hls-2061     mp4        1280x720   2061k , avc1.77.30, mp4a.40.2
hls-3061     mp4        1600x900   3061k , avc1.77.30, mp4a.40.2
hls-4560     mp4        1920x1080  4560k , avc1.77.30, mp4a.40.2 (best)
```
```
youtube-dl -F "http://www.hotstar.com/tv/ishqbaaaz/9576/shivaay-brings-gauri-home/1000176703"
[HotStar] 1000176703: Downloading JSON metadata
[HotStar] 1000176703: Downloading JIO JSON metadata
[HotStar] 1000176703: Downloading m3u8 information
[info] Available formats for 1000176703:
format code  extension  resolution note
hls-64       mp4        250x140      64k , avc1.66.30, mp4a.40.2
hls-121      mp4        320x180     121k , avc1.66.30, mp4a.40.2
hls-241      mp4        320x180     241k , avc1.66.30, mp4a.40.2
hls-461      mp4        416x234     461k , avc1.66.30, mp4a.40.2
hls-861      mp4        640x360     861k , avc1.66.30, mp4a.40.2
hls-1360     mp4        720x404    1360k , avc1.66.30, mp4a.40.2
hls-2061     mp4        1280x720   2061k , avc1.77.30, mp4a.40.2
hls-3061     mp4        1600x900   3061k , avc1.77.30, mp4a.40.2
hls-4561     mp4        1920x1080  4561k , avc1.77.30, mp4a.40.2 (best)
```
```
youtube-dl "http://www.hotstar.com/tv/sarabhai-vs-sarabhai-take-2/523/monisha-ki-mannat/1000175396"
[HotStar] 1000175396: Downloading JSON metadata
[HotStar] 1000175396: Downloading JIO JSON metadata
[HotStar] 1000175396: Downloading m3u8 information
[download] Destination: Monisha Ki Mannat - 1-1000175396.mp4
```
```
youtube-dl "http://www.hotstar.com/tv/ishqbaaaz/9576/shivaay-brings-gauri-home/1000176703"
[HotStar] 1000176703: Downloading JSON metadata
[HotStar] 1000176703: Downloading JIO JSON metadata
[HotStar] 1000176703: Downloading m3u8 information
[download] Destination: Shivaay Brings Gauri Home-1000176703.mp4
```

**Comment by shortthirdman** [comment]
@0880 @biezom Thanks for the help bro..I didn't know youtube-dl would be so helpful. Yoou saved me life. lol!

**Comment by nilmanimitra** [comment]
while i am trying to download a particular video from hotstar (link is http://www.hotstar.com/movies/xmen-apocalypse/1770015391 ) ,, it was showing "DRM protected"........please help me boss

**Comment by nilmanimitra** [comment]
![drm](https://user-images.githubusercontent.com/29285886/26944532-9fcc13c2-4ca6-11e7-82d7-5b9517733287.jpg)

**Comment by nilmanimitra** [comment]
@biezom please help me

**Comment by shortthirdman** [comment]
@nilmanimitra please use ffmpeg and youtube-dl for Hotstar. Example:
youtube-dl "http://www.hotstar.com/tv/ishqbaaaz/9576/shivaay-brings-gauri-home/1000176703"
youtube-dl -F "http://www.hotstar.com/tv/ishqbaaaz/9576/shivaay-brings-gauri-home/1000176703" //Available formats

**Comment by bentheguitarman** [comment]
shortthirdman I have tried youtube-dl and was working but no longer works (error below)

C:\Users\Ben\Downloads\Compressed\ffmpeg-20170503-a75ef15-win64-static\bin>youtube-dl.exe -v http://www.hotstar.com/tv/malcolm-in-the-middle/12117/grandma-sues/1000114289
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'http://www.hotstar.com/tv/malcolm-in-the-middle/12117/grandma-sues/1000114289']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.06.05
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg N-85750-ga75ef15, ffprobe N-85750-ga75ef15
[debug] Proxy map: {}
[HotStar] 1000114289: Downloading JSON metadata
[HotStar] 1000114289: Downloading JIO JSON metadata
[HotStar] 1000114289: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 502: Bad Gateway
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6q2mjw76\build\youtube_dl\YoutubeDL.py", line 761, in extract_info
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6q2mjw76\build\youtube_dl\extractor\common.py", line 433, in extract
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6q2mjw76\build\youtube_dl\extractor\hotstar.py", line 89, in _real_extract
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6q2mjw76\build\youtube_dl\extractor\common.py", line 1056, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

C:\Users\Ben\Downloads\Compressed\ffmpeg-20170503-a75ef15-win64-static\bin>pause
Press any key to continue . . .

**Comment by shortthirdman** [comment]
@bentheguitarman but I download videos from Hotstar using youtube-dl and ffmpeg only. It works for me..Have you installed python? which version are you using Python 2.x.x or Python 3.x.x?

**Comment by bentheguitarman** [comment]
@shortthirdman I think hotstar may be blocking my PC from accessing the video streams, you are in India correct? I live in another country and was using VPN and now it won't work anymore

**Comment by shortthirdman** [comment]
@bentheguitarman Oh that might be the case. I think you should give it a try again by signing up on Hotstar. See if this works.
